-- MySQL Script generated by MySQL Workbench
-- Fri Sep  4 17:38:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adakamar_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adakamar_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adakamar_db` DEFAULT CHARACTER SET utf8 ;
USE `adakamar_db` ;

-- -----------------------------------------------------
-- Table `adakamar_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NULL,
  `role` ENUM('admin', 'guest') NOT NULL DEFAULT 'guest',
  `google_id` VARCHAR(100) NULL,
  `avatar` VARCHAR(255) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `google_id_UNIQUE` (`google_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`kos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`kos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(170) NOT NULL,
  `description` TEXT NULL,
  `rules` TEXT NULL,
  `type` ENUM('putra', 'putri', 'campur') NOT NULL,
  `has_ac` TINYINT(1) NOT NULL DEFAULT 0,
  `has_wifi` TINYINT(1) NOT NULL DEFAULT 0,
  `has_private_bathroom` TINYINT(1) NOT NULL DEFAULT 0,
  `district` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `contact_name` VARCHAR(100) NOT NULL,
  `contact_whatsapp` VARCHAR(20) NOT NULL,
  `is_plus` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `rating_avg` DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  `review_count` INT NOT NULL DEFAULT 0,
  `views_count` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`kos_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`kos_prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kos_id` INT NOT NULL,
  `type` ENUM('harian', 'bulanan', 'tahunan') NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kos_prices_kos_idx` (`kos_id` ASC) VISIBLE,
  CONSTRAINT `fk_kos_prices_kos`
    FOREIGN KEY (`kos_id`)
    REFERENCES `adakamar_db`.`kos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`kos_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`kos_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kos_id` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kos_photos_kos_idx` (`kos_id` ASC) VISIBLE,
  CONSTRAINT `fk_kos_photos_kos`
    FOREIGN KEY (`kos_id`)
    REFERENCES `adakamar_db`.`kos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`facilities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category` ENUM('kamar', 'bersama', 'sekitar') NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`kos_facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`kos_facilities` (
  `kos_id` INT NOT NULL,
  `facility_id` INT NOT NULL,
  INDEX `fk_kos_facilities_kos_idx` (`kos_id` ASC) VISIBLE,
  INDEX `fk_facilities_kos_facilities_idx` (`facility_id` ASC) VISIBLE,
  PRIMARY KEY (`kos_id`, `facility_id`),
  CONSTRAINT `fk_kos_facilities_kos`
    FOREIGN KEY (`kos_id`)
    REFERENCES `adakamar_db`.`kos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facilities_kos_facilities`
    FOREIGN KEY (`facility_id`)
    REFERENCES `adakamar_db`.`facilities` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kos_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rating` TINYINT NOT NULL,
  `comment` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kos_reviews_idx` (`kos_id` ASC) VISIBLE,
  INDEX `fk_users_reviews_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_kos_reviews`
    FOREIGN KEY (`kos_id`)
    REFERENCES `adakamar_db`.`kos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_reviews`
    FOREIGN KEY (`user_id`)
    REFERENCES `adakamar_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`review_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`review_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review_id` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_reviews_photos_idx` (`review_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_reviews_photos`
    FOREIGN KEY (`review_id`)
    REFERENCES `adakamar_db`.`reviews` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adakamar_db`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adakamar_db`.`settings` (
  `key` VARCHAR(50) NOT NULL,
  `value` TEXT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
